project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - .nojekyll

website:
  title: "Sebastian Murk"
  site-url: https://sebastianmurk.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: news/index.qmd
        text: News
      - href: publications/index.qmd
        text: Publications
      - href: travel/index.qmd
        text: Travel
      - href: photos/index.qmd
        text: Photos

format:
  html:
    toc: false